"use client";

import { useState } from "react";
import type { SoapNote } from "@/types/soap";

type Props = {
  note: SoapNote;
};

export function ClinicalNote({ note }: Props) {
  const [copied, setCopied] = useState(false);

  const plainText = formatAsPlainText(note);

  async function copyToClipboard() {
    await navigator.clipboard.writeText(plainText);
    setCopied(true);
    setTimeout(() => setCopied(false), 1500);
  }

  function download() {
    const blob = new Blob([plainText], { type: "text/plain;charset=utf-8" });
    const url = URL.createObjectURL(blob);
    const a = document.createElement("a");
    a.href = url;
    a.download = `soap-note-${new Date().toISOString().slice(0, 19).replace(/[:T]/g, "-")}.txt`;
    document.body.appendChild(a);
    a.click();
    document.body.removeChild(a);
    URL.revokeObjectURL(url);
  }

  return (
    <section className="rounded-lg border border-emerald-900/50 bg-emerald-950/20 p-5">
      <div className="flex items-center justify-between mb-4">
        <h2 className="text-sm font-semibold uppercase tracking-wide text-emerald-400">
          SOAP Note
        </h2>
        <div className="flex items-center gap-2">
          <button
            type="button"
            onClick={copyToClipboard}
            className="text-xs px-3 py-1.5 rounded border border-slate-700 hover:border-slate-500 text-slate-200 transition"
          >
            {copied ? "Copied ✓" : "Copy"}
          </button>
          <button
            type="button"
            onClick={download}
            className="text-xs px-3 py-1.5 rounded border border-slate-700 hover:border-slate-500 text-slate-200 transition"
          >
            Download .txt
          </button>
        </div>
      </div>

      <div className="space-y-4 text-sm">
        <Section label="Subjective" body={note.subjective} />
        <Section label="Objective" body={note.objective} />
        <Section label="Assessment" body={note.assessment} />
        <Section label="Plan" body={note.plan} />
      </div>
    </section>
  );
}

function Section({ label, body }: { label: string; body: string }) {
  return (
    <div>
      <h3 className="text-xs font-bold uppercase tracking-wider text-emerald-400 mb-1">
        {label}
      </h3>
      <p className="whitespace-pre-wrap text-slate-200 leading-relaxed">{body}</p>
    </div>
  );
}

function formatAsPlainText(note: SoapNote): string {
  return [
    "SOAP NOTE",
    "=========",
    "",
    "SUBJECTIVE",
    note.subjective,
    "",
    "OBJECTIVE",
    note.objective,
    "",
    "ASSESSMENT",
    note.assessment,
    "",
    "PLAN",
    note.plan,
    "",
    "---",
    "Generated by MedScribe AI (demo — synthetic data only)",
  ].join("\n");
}
